# .github/workflows/pytest-matrix.yml
name: Pytest Matrix

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  python-tests:
    name: Pytest Matrix
    runs-on: ${{ inputs.runner }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.11, 3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run tests
        run: pytest tests/unit --cov=kataglyphispythonproject --cov-report=term-missing --junitxml=docs/test_results/report-${{ matrix.python-version }}.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: docs/test_results/
