# .github/workflows/build-docs.yml
name: Build Docs

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      SERVER:
        required: true
      USERNAME:
        required: true
      PW:
        required: true
jobs:
  build-docs:
    name: Build Documentation
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download coverage results
        uses: actions/download-artifact@v5.0.0
        with:
          name: reports-3.13-ubuntu-24.04
          path: docs/source/_static/coverage
      
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.10"

      - name: Prepare environment
        run: |
          python3 --version
          pip --version
          python3 -m pip install --upgrade pip
          pip install -e .[test,docs]

      - name: Copy docs
        run: |
          cp README.md docs/source/README.md
          cp CHANGELOG.md docs/source/CHANGELOG.md

      
      - name: Build web page
        run: |
          cd docs
          make html

      - name: 📂 Sync files to domain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PW }}
          local-dir: "./docs/build/html/"
