# .github/workflows/build-docs.yml
name: Build Docs

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      SERVER:
        required: true
      USERNAME:
        required: true
      PW:
        required: true
jobs:
  build-docs:
    name: Build Documentation
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Download coverage results
        uses: actions/download-artifact@v5.0.0
        with:
          name: reports-3.13-ubuntu-24.04
          path: docs/test_results
      
      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.10"

      - name: Prepare environment
        run: |
          python3 --version
          pip --version
          python3 -m pip install --upgrade pip
          pip install -e .[test,docs]

      - name: Copy docs
        run: |
          cp README.md docs/source/README.md
          cp CHANGELOG.md docs/source/CHANGELOG.md
     
      - name: Move test reports into Sphinx _static
        run: |
          set -e
          # where your artifact was downloaded
          SRC=docs/test_results

          # Sphinx source _static (adjust if your source dir is docs/sources)
          STATIC_DIR=docs/source/_static
          COVERAGE_DST=$STATIC_DIR/coverage

          mkdir -p "$COVERAGE_DST"

          echo "Looking for coverage HTML in $SRC ..."
          # common coverage layouts — adjust if your artifact structure differs:
          if [ -d "$SRC/coverage" ]; then
            cp -r "$SRC/coverage/." "$COVERAGE_DST/"
            echo "Copied $SRC/coverage -> $COVERAGE_DST/"
          elif [ -d "$SRC/htmlcov" ]; then
            cp -r "$SRC/htmlcov/." "$COVERAGE_DST/"
            echo "Copied $SRC/htmlcov -> $COVERAGE_DST/"
          else
            # try to find any index.html under SRC
            found=$(find "$SRC" -maxdepth 3 -type f -name index.html | head -n1 || true)
            if [ -n "$found" ]; then
              base=$(dirname "$found")
              cp -r "$base/." "$COVERAGE_DST/"
              echo "Copied discovered coverage HTML from $base -> $COVERAGE_DST/"
            else
              echo "No coverage HTML folder found in $SRC (checked coverage/ and htmlcov/)."
            fi
          fi

          # copy XML coverage if present and your index.rst links it
          if [ -f "$SRC/coverage.xml" ]; then
            cp "$SRC/coverage.xml" "$STATIC_DIR/coverage.xml"
            echo "Copied coverage.xml -> $STATIC_DIR/coverage.xml"
          fi
      
      - name: Build web page
        run: |
          cd docs
          make html

      - name: 📂 Sync files to domain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PW }}
          local-dir: "./docs/build/html/"
