name: Build Linux Binaries

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  build-package-binaries-linux-x86-64:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install system dependencies
        run: |
          chmod +x scripts/linux/setup-dependencies.sh
          ./scripts/linux/setup-dependencies.sh
          echo "/usr/bin" >> $GITHUB_PATH

      - name: Install uv (Astral)
        uses: astral-sh/setup-uv@v7.0.0
        with:
          python-version: 3.13t
          enable-cache: true

      # Optional: install Python pinned by project if you want: `uv python install`
      - name: Install project dependencies with uv (use lock if present)
        run: |
          if [ -f uv.lock ]; then
            echo "uv.lock found — using locked sync"
            uv sync --locked --dev --all-extras
          else
            echo "No uv.lock found — performing non-locked sync"
            uv sync --dev --all-extras
          fi

      - name: Build and rename Linux wheels
        env:
          CYTHONIZE: "True" 
        run: |
          # run the build *inside* the uv environment so packages are consistent
          uv run -m pip install --upgrade pip setuptools wheel build cython auditwheel
          # build in-place C extensions if your setup.py expects it
          uv run python setup.py build_ext --inplace
          # build wheel(s)
          uv run -m build -w --no-isolation
          # repair wheels to proper manylinux tags and put repaired wheels into dist/
          mkdir -p dist/repaired
          for whl in dist/*.whl; do
            # auditwheel will produce correct manylinux tags like manylinux2014_x86_64
            uv run auditwheel repair "$whl" -w dist/repaired || echo "auditwheel failed for $whl"
          done
          # move repaired wheels back up (or upload both original and repaired if you want)
          mv dist/repaired/* dist/ || true
          # list resulting wheels
          ls -lah dist

      - name: Store distribution artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist-artifact-${{ github.run_id }}
          path: dist/*
