# .github/workflows/ubuntu-24.04-arm.yml
name: Ubuntu 24.04 ARM Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml
    with:
      runner: ubuntu-24.04-arm

  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      runner: ubuntu-24.04-arm

  pytest-matrix:
    uses: ./.github/workflows/pytest-matrix.yml
    with:
      runner: ubuntu-24.04-arm
      python-versions: '["3.8", "3.9", "3.11", "3.12", "3.13"]'
      packagename: "kataglyphispythonproject"

  packaging-sources:
    uses: ./.github/workflows/packaging-sources.yml
    with:
      runner: ubuntu-24.04-arm

  packaging-binaries-linux:
    uses: ./.github/workflows/packaging-binaries-linux-x86-64.yml
    with:
      runner: ubuntu-24.04-arm
