# .github/workflows/ubuntu-24.04.yml
name: Windows 2025 Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    uses: ./.github/workflows/build-docs.yml
    with:
      runner: windows-2025

  pytest-matrix:
    uses: ./.github/workflows/pytest-matrix.yml
    with:
      runner: windows-2025

  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      runner: windows-2025

  packaging-sources:
    uses: ./.github/workflows/packaging-sources.yml
    with:
      runner: windows-2025

  packaging-binaries-linux:
    uses: ./.github/workflows/packaging-binaries-windows-x64.yml
    with:
      runner: windows-2025
